# Generated by Django 3.0.7 on 2020-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yararule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='rules',
            name='tags',
            field=models.ManyToManyField(to='yararule.Tags'),
        ),
    ]
