# Generated by Django 3.0.7 on 2020-06-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yararule', '0002_auto_20200621_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
